import { ApolloClient, InMemoryCache, gql } from '@apollo/client'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Nav } from "../components/Nav";
import { Footer } from "../components/Footer";
const inter = Inter({ subsets: ['latin'] })

import {graphQLUrl} from '../functions/functions'


export default function About({ data}) {
  return (
    <>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="antialiased text-gray-800 dark:bg-black dark:text-gray-400 flex flex-col min-h-screen">
  <div className="grow">
    <div className="container px-8 py-5 lg:py-8 mx-auto xl:px-5 max-w-screen-lg">
     <Nav/>
    </div>
    <div>
      <div className="container px-8 py-5 lg:py-8 mx-auto xl:px-5 max-w-screen-lg">
        <h1
          className="mt-2 mb-3 text-3xl font-semibold tracking-tight text-center lg:leading-snug text-brand-primary lg:text-4xl dark:text-white">
          { data.entry.title}</h1>
        <div className="text-center">
          <p className="text-lg">{ data.entry.intro_text}</p>
        </div>
        <div className="grid grid-cols-3 gap-5 mt-6 mb-16 md:mt-16 md:mb-32 md:gap-16">
          {}
          { data.entry.team_members.map( member =><Member member={member}/>)}
        </div>
        
      </div>
    </div>
  </div>
  <Footer/>
</div>

      </main>
    </>
  )
}


function Member(member) {
  return <div className="relative overflow-hidden rounded-md aspect-square odd:translate-y-10 odd:md:translate-y-16">
    
   
         <img
        alt="Mario Sanchez" sizes="(max-width: 320px) 100vw, 320px"
        src={member.member.image[0].src}
        decoding="async" data-nimg="fill"
        style={{ position: 'absolute', inset: '0px', boxSizing: 'border-box', padding: '0px', border: 'none', margin: 'auto', display: 'block', width: '0px', height: '0px', minWidth: '100%', maxWidth: '100%', minHeight: '100%', maxHeight: '100%', objectFit: 'cover' }} />
       
  </div>
}

export async function getServerSideProps(prop) {

  const client = new ApolloClient({
    uri: graphQLUrl(),
    cache: new InMemoryCache()
  });
  
  
  const { data } = await client.query({
    query: gql`query About {
      entry(id: "0a5eb8a3-319f-433a-8e29-ff9f624fe999") {
        id
        title
        ... on Entry_Pages_AboutBlueprint {
          intro_text
          team_members {
            ... on Set_TeamMembers_NewSet {
              name
              image {
                url
                permalink
                src(width: 285, height: 285)
              }
            }
          }
        }
      }
    }
    
        
    `
  });

  return {
    props : {
      data: data,
    }
  }
}
