import Head from "next/head";
import Image from "next/image";
import axios from 'axios'
import {backendURL} from '../functions/functions'

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { useState } from "react";

import { Nav } from "../components/Nav";
import { Footer } from "../components/Footer";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });


export default function Contact() {

  const { locale } = useRouter()

  const [state, setState] = useState({
    fullName: "",
    email: "",
    message: "",
  });
const [showThanks,setShowThanks] = useState(false )


  const [emailError, setEmailError] = useState(false);
  const [fullNameError, setFullNameError] = useState(false);
  const [messageError, setMessageError] = useState(false);

  const handleChange = (e) => {
    setState(() => {

      console.log(e.target.id,  e.target.value  )
      return {
        ...state,
        [e.target.id]: e.target.value,
      };
    });
  };

  const handleSubmit = () => {
    const {
      email,
      fullName,
      message
    } = state;
    setEmailError(email == "");
    setFullNameError(fullName == "");
    setMessageError(message == "");

    // country & jobTitle & subject
    if (email && fullName && message) {


      axios
        .post(
          `${backendURL()}/!/forms/contact_us`,
          {
            full_name: fullName,
            email: email,
            message: message,
          },
          {
            headers: {
              "X-Requested-With": "XMLHttpRequest",
            },
          }
        )
        .then(function (response) {
          if (response.data.success) {
            setShowThanks(true);
            setState({
              email: "",
              fullName: "",
              message: "",
            });
          } else {
            alert("Form could not submitted");
          }
        })
        .catch(function (error) {
        });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="antialiased text-gray-800 dark:bg-black dark:text-gray-400 flex flex-col min-h-screen">
          <div className="grow">
            <div className="container px-8 py-5 lg:py-8 mx-auto xl:px-5 max-w-screen-lg">
              {Nav()}
            </div>
            <div>
              <div className="container px-8 py-5 lg:py-8 mx-auto xl:px-5 max-w-screen-lg">
                <h1 className="mt-2 mb-3 text-3xl font-semibold tracking-tight text-center lg:leading-snug text-brand-primary lg:text-4xl dark:text-white">
                  Contact
                </h1>
                <div className="text-center">
                  <p className="text-lg">We are a here to help.</p>
                </div>
                <div className="grid my-10 md:grid-cols-2">
                  <div className="my-10">

                    { locale  == 'en' ? <h2 className="text-2xl font-semibold dark:text-white">
                      Contact US
                    </h2>: <h2 className="text-2xl font-semibold dark:text-white">
                    تواصل معنا  
                    </h2>}
                    
                    <p className="max-w-sm mt-5">
                      Have something to say? We are here to help. Fill up the
                      form or send email or call phone.
                    </p>
                    <div className="mt-5">
                      <div className="flex items-center mt-2 space-x-2 text-dark-600 dark:text-gray-400">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={2}
                          stroke="currentColor"
                          aria-hidden="true"
                          className="w-4 h-4"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
                          />
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
                          />
                        </svg>
                        <span>1734 Sanfransico, CA 93063</span>
                      </div>
                      <div className="flex items-center mt-2 space-x-2 text-dark-600 dark:text-gray-400">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={2}
                          stroke="currentColor"
                          aria-hidden="true"
                          className="w-4 h-4"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                          />
                        </svg>
                        <a href="mailto:">hello@domain.com</a>
                      </div>
                      <div className="flex items-center mt-2 space-x-2 text-dark-600 dark:text-gray-400">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={2}
                          stroke="currentColor"
                          aria-hidden="true"
                          className="w-4 h-4"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                          />
                        </svg>
                        <a href="tel:+1 (987) 4587 899">+1 (987) 4587 899</a>
                      </div>
                    </div>
                  </div>
                  <div>
                  { showThanks ? <div>
                        <h1 className='mt-10 xl:text-3xl medium-font text-grey text-xl text-center'>Thanks</h1>
                        <p className='text-lg light-font text-grey mt-2 text-center'>We will talk</p>
                       
                    </div>: <form
                      onSubmit={(e) => {
                        e.preventDefault();
                      }}
                      className="my-10"
                    >
                      <input
                        type="checkbox"
                        id
                        className="hidden"
                        name="botcheck"
                        style={{ display: "none" }}
                      />
                      <div className="mb-5">
                        <input
                          onChange={handleChange}
                          id="fullName"
                          type="text"
                          placeholder="Full Name"
                          autoComplete="false"
                          className="w-full px-4 py-3 border-2 placeholder:text-gray-800 dark:text-white rounded-md outline-none dark:placeholder:text-gray-200 dark:bg-gray-900   focus:ring-4  border-gray-300 focus:border-gray-600 ring-gray-100 dark:border-gray-600 dark:focus:border-white dark:ring-0"
                          name="fullName"
                        />
                       {fullNameError && <span className="">Enter Name</span>}

                      </div>
                      <div className="mb-5">
                        <label htmlFor="email_address" className="sr-only">
                          Email Address
                        </label>
                        <input
                          onChange={handleChange}
                          id="email"
                          type="email"
                          placeholder="Email Address"
                          name="email"
                          autoComplete="false"
                          className="w-full px-4 py-3 border-2 placeholder:text-gray-800 dark:text-white rounded-md outline-none dark:placeholder:text-gray-200 dark:bg-gray-900   focus:ring-4  border-gray-300 focus:border-gray-600 ring-gray-100 dark:border-gray-600 dark:focus:border-white dark:ring-0"
                        />
                         {emailError && <span className="">Enter Email Address</span>}

                      </div>
                      <div className="mb-3">
                        <textarea
                          onChange={handleChange}
                          name="message"
                          placeholder="Your Message"
                          id="message"
                          className="w-full px-4 py-3 border-2 placeholder:text-gray-800 dark:text-white dark:placeholder:text-gray-200 dark:bg-gray-900   rounded-md outline-none  h-36 focus:ring-4  border-gray-300 focus:border-gray-600 ring-gray-100 dark:border-gray-600 dark:focus:border-white dark:ring-0"
                          defaultValue={""}
                        />
                        {messageError && <span className="">Enter Message</span>}
                      </div>
                      <button
                        onClick={handleSubmit} 
                        type="submit"
                        className="w-full py-4 font-semibold text-white transition-colors bg-gray-900 rounded-md hover:bg-gray-800 focus:outline-none focus:ring-offset-2 focus:ring focus:ring-gray-200 px-7 dark:bg-white dark:text-black "
                      >
                        Send Message
                      </button>
                    </form> }
                  </div>
                </div>
              </div>
            </div>
          </div>
         <Footer />
        </div>
      </main>
    </>
  );
}
